/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class FrmMenuEmpleado extends javax.swing.JFrame {
    private UsuarioEmpleado empleado;
    private Banco banco;
    private GestorUsuarios gestor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuEmpleado.class.getName());

    /**
     * Creates new form FrmMenuEmpleado
     */
    public FrmMenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistroCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jButtonRegistroCuenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDeposito = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnHistorialCuenta = new javax.swing.JButton();
        btnVerAcciones = new javax.swing.JButton();
        btnVerClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRegistroCliente.setText("Registar Cliente");
        jButtonRegistroCliente.addActionListener(this::jButtonRegistroClienteActionPerformed);

        btnModificarCliente.setText("Modificar cliente");
        btnModificarCliente.addActionListener(this::btnModificarClienteActionPerformed);

        btnEliminarCliente.setText("Eliminar cliente");
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);

        jButtonRegistroCuenta.setText("Registrar cuenta a cliente");
        jButtonRegistroCuenta.addActionListener(this::jButtonRegistroCuentaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRegistroCuenta)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarCliente)
                            .addComponent(btnEliminarCliente)
                            .addComponent(jButtonRegistroCliente))
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonRegistroCliente)
                .addGap(18, 18, 18)
                .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistroCuenta)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Gestion", jPanel1);

        btnDeposito.setText("Procesar depósito");
        btnDeposito.addActionListener(this::btnDepositoActionPerformed);

        btnRetiro.setText("Procesar retiro");
        btnRetiro.addActionListener(this::btnRetiroActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnRetiro)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeposito)
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnDeposito)
                .addGap(46, 46, 46)
                .addComponent(btnRetiro)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Transaccion", jPanel2);

        btnHistorialCuenta.setText("Ver historial de una cuenta");
        btnHistorialCuenta.addActionListener(this::btnHistorialCuentaActionPerformed);

        btnVerAcciones.setText("Ver mis acciones");
        btnVerAcciones.addActionListener(this::btnVerAccionesActionPerformed);

        btnVerClientes.setText("Ver lista de clientes");
        btnVerClientes.addActionListener(this::btnVerClientesActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerClientes)
                            .addComponent(btnVerAcciones)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnHistorialCuenta)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnHistorialCuenta)
                .addGap(27, 27, 27)
                .addComponent(btnVerAcciones)
                .addGap(18, 18, 18)
                .addComponent(btnVerClientes)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Varios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        FrmEliminarCliente pestaña = new FrmEliminarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void jButtonRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroClienteActionPerformed
        JFrameRegistrarCliente pestaña = new JFrameRegistrarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_jButtonRegistroClienteActionPerformed

    private void jButtonRegistroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroCuentaActionPerformed
        JFrameRegistrarCuenta pestaña = new JFrameRegistrarCuenta();
        pestaña.setVisible(true);
    }//GEN-LAST:event_jButtonRegistroCuentaActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        FrmDepositoEmpleado pestaña = new FrmDepositoEmpleado(empleado,banco,gestor);
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        FrmRetiroEmpleado pestaña = new FrmRetiroEmpleado(empleado,banco,gestor);
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        FrmModificarCliente pestaña = new FrmModificarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnHistorialCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialCuentaActionPerformed
        JFrameHistorialEmpleado pestaña = new JFrameHistorialEmpleado();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnHistorialCuentaActionPerformed

    private void btnVerAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAccionesActionPerformed
        FrmMostrarAcciones pestaña = new FrmMostrarAcciones();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnVerAccionesActionPerformed

    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        FrmMostrarClientes pestaña = new FrmMostrarClientes();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnVerClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnHistorialCuenta;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnVerAcciones;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JButton jButtonRegistroCliente;
    private javax.swing.JButton jButtonRegistroCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
}
