/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class FrmMenuAdmin extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName());

    /**
     * Creates new form FrmMenuAdmin
     */

    public FrmMenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        jPanel2 = new javax.swing.JPanel();
        jButtonRegistrarCliente = new javax.swing.JButton();
        jButtonRegistarEmpleado = new javax.swing.JButton();
        jButtonRegistrarCuenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnModificarEmpleado = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEliminarCliente = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnMostrarUsuarios = new javax.swing.JButton();
        btnMostrarClientes = new javax.swing.JButton();
        btnMostrarEmpleados = new javax.swing.JButton();
        btnMostrarTransacciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRegistrarCliente.setText("Registar Cliente");
        jButtonRegistrarCliente.addActionListener(this::jButtonRegistrarClienteActionPerformed);

        jButtonRegistarEmpleado.setText("Registar Empleado");
        jButtonRegistarEmpleado.addActionListener(this::jButtonRegistarEmpleadoActionPerformed);

        jButtonRegistrarCuenta.setText("Registar Cuenta a Cliente");
        jButtonRegistrarCuenta.addActionListener(this::jButtonRegistrarCuentaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButtonRegistrarCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButtonRegistarEmpleado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButtonRegistrarCuenta)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonRegistrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistarEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarCuenta)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Registrar", jPanel2);

        btnModificarEmpleado.setText("Modificar empleado (por ID)");
        btnModificarEmpleado.addActionListener(this::btnModificarEmpleadoActionPerformed);

        btnModificarCliente.setText("Modificar cliente (por ID)");
        btnModificarCliente.addActionListener(this::btnModificarClienteActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnModificarCliente)
                .addGap(41, 41, 41)
                .addComponent(btnModificarEmpleado)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnModificarCliente))
                .addGap(158, 158, 158))
        );

        tabbedPaneCustom1.addTab("Modificar", jPanel3);

        btnEliminarCliente.setText("Eliminar cliente (por ID)");
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);

        btnEliminarEmpleado.setText("Eliminar empleado (por ID)");
        btnEliminarEmpleado.addActionListener(this::btnEliminarEmpleadoActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnEliminarCliente)
                .addGap(57, 57, 57)
                .addComponent(btnEliminarEmpleado)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEmpleado)
                    .addComponent(btnEliminarCliente))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Eliminar", jPanel4);

        btnMostrarUsuarios.setText("Mostrar usuarios");
        btnMostrarUsuarios.addActionListener(this::btnMostrarUsuariosActionPerformed);

        btnMostrarClientes.setText("Mostrar clientes");
        btnMostrarClientes.addActionListener(this::btnMostrarClientesActionPerformed);

        btnMostrarEmpleados.setText("Mostrar empleados");
        btnMostrarEmpleados.addActionListener(this::btnMostrarEmpleadosActionPerformed);

        btnMostrarTransacciones.setText("Mostrar transacciones");
        btnMostrarTransacciones.addActionListener(this::btnMostrarTransaccionesActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarUsuarios)
                    .addComponent(btnMostrarEmpleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnMostrarTransacciones)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnMostrarClientes)
                        .addGap(65, 65, 65))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarUsuarios)
                    .addComponent(btnMostrarClientes))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarEmpleados)
                    .addComponent(btnMostrarTransacciones))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Mostrar", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarClienteActionPerformed
        JFrameRegistrarCliente pestaña = new JFrameRegistrarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarClienteActionPerformed

    private void jButtonRegistarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarEmpleadoActionPerformed
        JFrameRegistrarEmpleado pestaña = new JFrameRegistrarEmpleado();
        pestaña.setVisible(true);
    }//GEN-LAST:event_jButtonRegistarEmpleadoActionPerformed

    private void jButtonRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCuentaActionPerformed
        JFrameRegistrarCuenta pestaña = new JFrameRegistrarCuenta();
        pestaña.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarCuentaActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        FrmModificarEmpleado pestaña = new FrmModificarEmpleado();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnMostrarTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTransaccionesActionPerformed
        JFrameHistorialEmpleado pestaña = new JFrameHistorialEmpleado();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnMostrarTransaccionesActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        FrmModificarCliente pestaña = new FrmModificarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        FrmEliminarCliente pestaña = new FrmEliminarCliente();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed
        FrmMostrarUsuarios pestaña = new FrmMostrarUsuarios();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed

    private void btnMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClientesActionPerformed
        FrmMostrarClientes pestaña = new FrmMostrarClientes();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnMostrarClientesActionPerformed

    private void btnMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosActionPerformed
        FrmMostrarEmpleados pestaña = new FrmMostrarEmpleados();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnMostrarEmpleadosActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        FrmEliminarEmpleado pestaña = new FrmEliminarEmpleado();
        pestaña.setVisible(true);
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnMostrarClientes;
    private javax.swing.JButton btnMostrarEmpleados;
    private javax.swing.JButton btnMostrarTransacciones;
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JButton jButtonRegistarEmpleado;
    private javax.swing.JButton jButtonRegistrarCliente;
    private javax.swing.JButton jButtonRegistrarCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
}
