
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jonahtan
 */
public class JFrameRegistrarCuenta extends javax.swing.JFrame {

    private Banco banco;
    CuentaCon cu = new CuentaCon();
    /**
     * Creates new form JFrameRegistrarCuenta
     */
    public JFrameRegistrarCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTIdCuenta = new javax.swing.JTextField();
        JTIdCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JBRegistrarCuenta = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registrar cliente");

        JTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNombreActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel.setText("Registrar cuenta a cliente");

        jLabel2.setText("ID del cliente:");

        JTIdCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTIdCuentaActionPerformed(evt);
            }
        });

        JTIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTIdClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("ID de la cuenta");

        JBRegistrarCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBRegistrarCuenta.setText("Registrar");
        JBRegistrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegistrarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(JBRegistrarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(JBRegistrarCuenta)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNombreActionPerformed

    private void JTIdCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTIdCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTIdCuentaActionPerformed

    private void JTIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTIdClienteActionPerformed

    private void JBRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegistrarCuentaActionPerformed
        // TODO add your handling code here:
        try {
            //SE OBTIENEN LOS DATOS
            String idCliente = JTIdCliente.getText();
            String idCuenta = JTIdCuenta.getText();

            //SE VALIDA QUE NO ESTEN VACIOS
            if (idCliente.isEmpty() || idCuenta.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ambos campos son obligatorios",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            

            //SE BUSCA AL CLIENTE
//            Cliente cliente = banco.buscarCliente(idCliente);
//            if (cliente == null) {
//                javax.swing.JOptionPane.showMessageDialog(this,
//                        "No existe un cliente con el ID: " + idCliente + "\n"
//                        + "Debe registrar al cliente primero.",
//                        "Cliente No Encontrado",
//                        javax.swing.JOptionPane.WARNING_MESSAGE);
//                return;
//            }

            //SE CREA LA CUENTA
            CuentaCliente nuevacuenta = new CuentaCliente(idCliente, idCuenta);
            nuevacuenta.setId_cliente(JTIdCliente.getText());
            nuevacuenta.setId_cuenta(JTIdCuenta.getText());
            cu.RegistrarCuenta(nuevacuenta);
//            Cuenta nuevaCuenta = new Cuenta(idCuenta, 0.0);
//            banco.registrarCuenta(cliente, nuevaCuenta);

            //SE MUESTRA EL MENSAJE DE EXITO
            javax.swing.JOptionPane.showMessageDialog(this,
                    "CUENTA REGISTRADA EXITOSAMENTE \n"
                    + "ID Cliente: " + idCliente + "\n"
                    + "ID Cuenta: " + idCuenta + "\n"
                    + "Saldo Inicial: $0.00\n\n"
                    + "La cuenta ha sido asociada al cliente.",
                    "Registro Completado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //SE LIMPIA TODO
            JTIdCliente.setText("");
            JTIdCuenta.setText("");
            JTIdCliente.requestFocus();

        } catch (IllegalArgumentException ex) {
            //ERRORES EN EL CONSTRUCTOR AL REGISTRAR
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error en datos de la cuenta: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            //OTROS ERRORES
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Error del Sistema",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBRegistrarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBRegistrarCuenta;
    private javax.swing.JTextField JTIdCliente;
    private javax.swing.JTextField JTIdCuenta;
    private javax.swing.JTextField JTNombre;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
