
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class FrmEliminarCliente extends javax.swing.JFrame {
    DefaultTableModel modelo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEliminarCliente.class.getName());
    ClienteCon cliente = new ClienteCon();
    /**
     * Creates new form FrmEliminarCliente
     */
    public FrmEliminarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTIdCliente = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDatos = new javax.swing.JTable();
        BtnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Eliminar Cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Id de Cliente");

        JTIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        JTIdCliente.addActionListener(this::JTIdClienteActionPerformed);

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        JTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(JTDatos);

        BtnMostrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnMostrar.setText("Buscar");
        BtnMostrar.addActionListener(this::BtnMostrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(BtnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(BtnMostrar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTIdClienteActionPerformed

    public void MostrarDatos(){
        try {
            //OBTIENE LOS VALORES DE LOS JTEXTFIELD
            String id = JTIdCliente.getText();

            //VALIDA QUE NO ESTE VACIO
            if (id.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ingrese su ID",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Cliente mostrarCliente = new Cliente(id);
            mostrarCliente.setId(JTIdCliente.getText());
            List<Cliente> listCl = cliente.MostrarDatos(mostrarCliente);
            modelo = (DefaultTableModel) JTDatos.getModel();
            Object[] ob = new Object[3];
            for (int i = 0; i < listCl.size(); i++) {
                ob[0] = listCl.get(i).getId();
                ob[1] = listCl.get(i).getNombre();
                ob[2] = listCl.get(i).getDireccion();
                modelo.addRow(ob);
            }
            JTDatos.setModel(modelo);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try {
            String idCliente = JTIdCliente.getText();
            
            if (idCliente.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El campo es obligatorio",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }else {
                int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el cliente?");
                if (pregunta == 0) {
                    cliente.EliminarCliente(idCliente);
                    JTIdCliente.setText("");
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Error del Sistema",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        // TODO add your handling code here:
        MostrarDatos();
    }//GEN-LAST:event_BtnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JTable JTDatos;
    private javax.swing.JTextField JTIdCliente;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
